-- MYSQL WORKBENCH FORWARD ENGINEERING

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- SCHEMA PI_6_INSIDE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- SCHEMA PI_6_INSIDE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PI_6_INSIDE` DEFAULT CHARACTER SET UTF8 ;
USE `PI_6_INSIDE` ;

-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_TIPO_USUA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_TIPO_USUA` (
  `ID_TIPO` INT NOT NULL AUTO_INCREMENT,
  `DESC_TIPO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_CARGO_FUNC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_CARGO_FUNC` (
  `ID_CARGO_FUNC` INT NOT NULL AUTO_INCREMENT,
  `DESC_CARGO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_CARGO_FUNC`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_USUARIO` (
  `LOGIN` VARCHAR(40) NOT NULL,
  `SENHA` VARCHAR(15) NOT NULL,
  `ID_TIPO` INT NOT NULL,
  `NOME` VARCHAR(130) NOT NULL,
  `EMAIL` VARCHAR(100) NULL,
  `CPF` VARCHAR(11) NULL,
  `RG` VARCHAR(11) NULL,
  `CELULAR` VARCHAR(11) NULL,
  `TELEFONE` VARCHAR(10) NULL,
  `ID_CARGO_FUNC` INT NOT NULL,
  `OBSERVACOES` VARCHAR(500) NULL,
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC),
  PRIMARY KEY (`LOGIN`),
  INDEX `FK_TB_USUARIO_TB_TIPO_USUA_IDX` (`ID_TIPO` ASC),
  INDEX `FK_TB_USUARIO_TB_CARGO_FUNC1_IDX` (`ID_CARGO_FUNC` ASC),
  CONSTRAINT `FK_TB_USUARIO_TB_TIPO_USUA`
    FOREIGN KEY (`ID_TIPO`)
    REFERENCES `PI_6_INSIDE`.`TB_TIPO_USUA` (`ID_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_USUARIO_TB_CARGO_FUNC1`
    FOREIGN KEY (`ID_CARGO_FUNC`)
    REFERENCES `PI_6_INSIDE`.`TB_CARGO_FUNC` (`ID_CARGO_FUNC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(130) NOT NULL,
  `REPRESENTANTE` VARCHAR(80) NULL,
  `TELEFONE` VARCHAR(11) NULL,
  `EMAIL_REP` VARCHAR(80) NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_PROJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_PROJETO` (
  `ID_PROJETO` INT NOT NULL AUTO_INCREMENT,
  `DESC_PROJETO` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(40) NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `DETALHE` VARCHAR(200) NOT NULL,
  `ATIVIDADE` VARCHAR(80) NULL,
  `INICIO_PROJ` DATE NOT NULL,
  `FIM_PROJ` DATE NOT NULL,
  `HORAS` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`ID_PROJETO`),
  INDEX `FK_TB_PROJETO_TB_USUARIO1_IDX` (`LOGIN` ASC),
  INDEX `FK_TB_PROJETO_TB_CLIENTE1_IDX` (`ID_CLIENTE` ASC),
  CONSTRAINT `FK_TB_PROJETO_TB_USUARIO1`
    FOREIGN KEY (`LOGIN`)
    REFERENCES `PI_6_INSIDE`.`TB_USUARIO` (`LOGIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_PROJETO_TB_CLIENTE1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `PI_6_INSIDE`.`TB_CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_DEMANDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_DEMANDA` (
  `ID_DEMANDA` INT NOT NULL AUTO_INCREMENT,
  `DESC_DEMANDA` VARCHAR(70) NOT NULL,
  `DETALHES` VARCHAR(200) NOT NULL,
  `ID_PROJETO` INT NOT NULL,
  `LOGIN` VARCHAR(40) NOT NULL,
  `DURACAO` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`ID_DEMANDA`),
  INDEX `FK_TB_DEMANDA_TB_PROJETO1_IDX` (`ID_PROJETO` ASC),
  INDEX `FK_TB_DEMANDA_TB_USUARIO1_IDX` (`LOGIN` ASC),
  CONSTRAINT `FK_TB_DEMANDA_TB_PROJETO1`
    FOREIGN KEY (`ID_PROJETO`)
    REFERENCES `PI_6_INSIDE`.`TB_PROJETO` (`ID_PROJETO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_DEMANDA_TB_USUARIO1`
    FOREIGN KEY (`LOGIN`)
    REFERENCES `PI_6_INSIDE`.`TB_USUARIO` (`LOGIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_PRODUCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_PRODUCAO` (
  `ID_PRODUCAO` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `HR_INICIO` DATETIME NOT NULL,
  `HR_PAUSA` DATETIME NULL,
  `HR_RET_PAUSA` DATETIME NULL,
  `HR_FIM` DATETIME NULL,
  `ID_DEMANDA` INT NOT NULL,
  PRIMARY KEY (`ID_PRODUCAO`),
  INDEX `FK_TB_PRODUCAO_TB_DEMANDA1_IDX` (`ID_DEMANDA` ASC),
  CONSTRAINT `FK_TB_PRODUCAO_TB_DEMANDA1`
    FOREIGN KEY (`ID_DEMANDA`)
    REFERENCES `PI_6_INSIDE`.`TB_DEMANDA` (`ID_DEMANDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_COMENTARIO` (
  `ID_COMENTARIO` INT NOT NULL AUTO_INCREMENT,
  `COMENTARIO` VARCHAR(400) NOT NULL,
  `DT_COMENTARIO` DATETIME NOT NULL,
  PRIMARY KEY (`ID_COMENTARIO`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_ARQUIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_ARQUIVO` (
  `ID_ARQUIVO` INT NOT NULL AUTO_INCREMENT,
  `DIRETORIO_ARQ` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ID_ARQUIVO`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `PI_6_INSIDE`.`TB_RECURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PI_6_INSIDE`.`TB_RECURSO` (
  `ID_RECURSO` INT NOT NULL AUTO_INCREMENT,
  `ID_DEMANDA` INT NOT NULL,
  `ID_COMENTARIO` INT NOT NULL,
  `ID_ARQUIVO` INT NOT NULL,
  PRIMARY KEY (`ID_RECURSO`),
  INDEX `FK_TB_RECURSO_TB_DEMANDA1_IDX` (`ID_DEMANDA` ASC),
  INDEX `FK_TB_RECURSO_TB_COMENTARIO1_IDX` (`ID_COMENTARIO` ASC),
  INDEX `FK_TB_RECURSO_TB_ARQUIVO1_IDX` (`ID_ARQUIVO` ASC),
  CONSTRAINT `FK_TB_RECURSO_TB_DEMANDA1`
    FOREIGN KEY (`ID_DEMANDA`)
    REFERENCES `PI_6_INSIDE`.`TB_DEMANDA` (`ID_DEMANDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_RECURSO_TB_COMENTARIO1`
    FOREIGN KEY (`ID_COMENTARIO`)
    REFERENCES `PI_6_INSIDE`.`TB_COMENTARIO` (`ID_COMENTARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_RECURSO_TB_ARQUIVO1`
    FOREIGN KEY (`ID_ARQUIVO`)
    REFERENCES `PI_6_INSIDE`.`TB_ARQUIVO` (`ID_ARQUIVO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ALIMENTANDO TB DE TIPO USUARIO
INSERT INTO TB_TIPO_USUA (DESC_TIPO) VALUES ('ADMINISTRADOR');
INSERT INTO TB_TIPO_USUA (DESC_TIPO) VALUES ('ANALISTA');



-- ALIMENTANDO TB DE TIPO DE CARGO
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('DIRETOR');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('GERENTE');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('SUPERVISOR');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('ANALISTA SENIOR');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('ANALISTA PLENO');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('ANALISTA JUNIOR');
INSERT INTO TB_CARGO_FUNC (DESC_CARGO) VALUES ('ESTAGIARIO');

-- TABELA DE USUARIO
INSERT INTO TB_USUARIO (LOGIN, SENHA, ID_TIPO, NOME, EMAIL, CELULAR, TELEFONE, CPF, RG, ID_CARGO_FUNC, OBSERVACOES) VALUES ('master', '1234', 1, 'Admin', 'admin.master@gmail.com', '11970707070', '1136907070', '12345678901', '789234560', 1, '(Adm');
INSERT INTO TB_USUARIO (LOGIN, SENHA, ID_TIPO, NOME, EMAIL, CELULAR, TELEFONE, CPF, RG, ID_CARGO_FUNC, OBSERVACOES) VALUES ('joao.silva', '123@abc', 2, 'João da Silva', 'joao.silva@gmail.com', '11987654321', '1147654321', '12345678900', '111234560', 6, '(possui grande conhecimento na instalação de sistemas operacionais Windows');

-- CLIENTE
INSERT INTO TB_CLIENTE (NOME_CLIENTE) VALUES ('Cartório de Registro de Imóveis de São Paulo');


-- PROJETO 
INSERT INTO TB_PROJETO (ID_PROJETO, DESC_PROJETO, LOGIN, ID_CLIENTE, DETALHE, ATIVIDADE,INICIO_PROJ, FIM_PROJ, HORAS) VALUES (1234, 'Reestruturação do ambiente de TI', 'master', 1, 'Reestruturar o ambiente físico de TI com a instalação de novo cabeamento e novo parque de máquinas', 'Instalar sistema operacional Windows 10 nas 50 estações', '2019-01-01', '2019-02-01', '160');

-- TABELA DE DEMANDA
INSERT INTO TB_DEMANDA (DESC_DEMANDA, DETALHES, ID_PROJETO, LOGIN, DURACAO) VALUES ('Instalar sistema operacional', 'Instalação do sistema operacional Windows 10 nas 50 estações de trabalho', 1234, 'master', '40');

